// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------




[System.ServiceModel.ServiceContractAttribute(Namespace="http://zerosumtech.com/stockestimator/1/0")]
public interface IEstimatorService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/Ping", ReplyAction="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/PingResponse")]
    bool Ping();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/Update", ReplyAction="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/UpdateResponse")]
    void Update();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/IsServiceCacheCurrent", ReplyAction="http://zerosumtech.com/stockestimator/1/0/IEstimatorService/IsServiceCacheCurrentResponse")]
    bool IsServiceCacheCurrent();
}

public interface IEstimatorServiceChannel : IEstimatorService, System.ServiceModel.IClientChannel {
}

public class EstimatorServiceClient : System.ServiceModel.ClientBase<IEstimatorService>, IEstimatorService {
    
    public EstimatorServiceClient() {
    }
    
    public EstimatorServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public EstimatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public EstimatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public EstimatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public bool Ping() {
        return base.Channel.Ping();
    }
    
    public void Update() {
        base.Channel.Update();
    }
    
    public bool IsServiceCacheCurrent() {
        return base.Channel.IsServiceCacheCurrent();
    }
}
